before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
cache: bundler
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  run: rake db:migrate
  api_key:
    secure: gITwJ973sjz+3et31kMOFAlmHQeBD5J2lomrLj6Mnj5x23uOIXG8nUFi7p6/WeKKJ51Lq98GeI7QuDGIwECKeJU18bmFwMpta7CV8tmJUkWsRhRLeYWlGTkAfTleUGzFdzAOiv9jEctiXiBE2ok/ISpjmO+0xVR6Mil+XsQ0RhzJGqjMekdNjTi2waDG6vwBH/Jjz4Fyws7PhgtPMde/gEDuHFKQZTkfWZODJYl9bm0J8jMqYQYw+q6LtF5M5Bl+fLLVgDbSjlQ2aghPwfWkXDMudGJISFJ6uP2lGWmUgw5K+lSg10zhsUTdlPMIPyesvZZgmdUet2H903hoEZpN6VW5s8v+Iy8Aju2xtKijLSvKvhhPbSXy24f5kKTURikALdyvSYq6SuB9HvWDOEPD0C1qjRt0Qaer5yW1SHMMiH1799V2qMjLD+/M5v0c7VjZ3AlBw1nT+7R8MRlZSLnCML2YAhKFcROGE9vI4ryBoItaa0Tix647mdGXs2RGid1/kVzeiE0pp+zK3TdLLHHa005oAHdjEZV/n1VwL7hf+jhsattVovRW/gTGPJ7knYP9Qu54MggxeYGXV1wQhrIOADP37K2Jpjk1R0V1GYZovx7hPR7WK3fIk6lNH6g7C/V5UZRFFAdO90HkAK0QZN00CeLGxplF8L2lvBtDoLCAJvE=
