before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  api_keyrspec:
    secure: HhCbkZ3gAyztbiU/O3EkMyrISlSCcHnQXCE6PPSoxP+TiIgHpY3z/Z5K3IuKsjzK4ehiz9uMqE4YuGSXRlKZNE2o46qeCbH+LBS97Lr9r6sUGKeuQyOTqDDs1ziMGYnZSjdw3LMN/MPwzyu4zZRLv51y+fOmgRqis+wB+SUkvo7w3SnfwGSbOBFKx6wOVZea2u3c9gz/vO2bquVFrMwNC3P0zBlN/N4B5KzPjYnNHRaCO5ERkexKfXEnXgqg6gzWXg7bomNsnI02T4+VFxESVO+jfg4w6C46+lV0v59RVb8BoaXa/A6HiW47bTbNymm2y7ENKdlfphTUQHqY2xLgJz/iwAC4akSrbNIV0sRAGeBjRYEOI3cLt7lsNJl7x0HyFWI0Hn/qD3fMeDXvvaOHEuyPbTcV2DJpVvgMEYR5eLw25Ry81kEMu1J2/QH8dPmaSYHkHKk84o89hLqsa6kxzR7B2ju0oXZrTnSuMWEjUHNQQb3npTXsuCGVVsW7yIzNO0O+k+K6WR3FeHaZUYuy2/586RnpAIXz3BgxzIjpuayC1YRMrWC5kAIbaQqd0kqVHzoWwL+pLsj++drL1z7iuzYNDzXEF8qGyAtVzpKDXYiJ7X4RZKsnb3jNi5HbIz8Vt2p+TOGM9ex3b6mDDCU2xnwIJWhPs3EFT2784BVbwUk=
