before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
cache: bundler
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Rkl0GMsHMrMnxlO3iLFqPwlPneLSGeTRc+x/g63wg9iUWp1QVw7zCGYngIuxpWE7KwBkjbUYLzWJ6bWfBA5UexTAIYcNDPLgwUZ5x1VyQCsno67w9qyTFHD8exyoIFcLWmRmxfWQwfRzmfg4bVKC9Q5ZaOcptEbX3l1yQSKX1eX0VFIfj2hnqHyYo9JpIvzuzPrTWFmi/1sifZjP4Q94KgsqFL00WSOG8DixCCKyC6GO07RwUwyZl4XmOFsiRq8h5MCcANCFFkH4BWCa4yrxmqNwVLHXcbb8PaqymcZa05ee1c5ZbuybgyjFaLBnyDp3AtL5ESfo53ZhqyHBR8Hh+fzGYa6EbDJcTTcWa2+XqXuigNla9+x7HnhPntxcEuKHDWWgcH0VRewIKqc9MZARkBoPnnGnj0OD7KDiyalnQuh1dOKtllP9C7fnNvVkMsyLgxpUAfjBon3ZvxXEVgLW8cVwdJdikf7AFRd/Gi47vmCc6AjMOLnU69IiRRtvc8e0VCCaRZZTqMWj+YhRBFApaVbx2cfRumE7D/uzKV5lO9KGvO03w79/nteviVlq1VzlmaJP8nfuZPmjQJX/pq2vYX8w6o1cRPZIDlWMxhP9Bn63O1Odw0jTeJtlqdq6cRAlQlPIhOKGddLvr1GEjUb2qTg1Nosd7vVB9weaTbimDM8=
  run: rake db:migrate
